[build]
  base = "/"
  publish = "Frontend/dist"
  command = "bash build.sh Frontend"

[build.environment]
  NODE_VERSION = "18"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
